let dimension = 15;
let map = new Map(dimension);
map.create();
let personnage = map.initPersonnage();
map.initEventListeners();
map.populateBackground();
let wall = new Block(10,4,"wall");
let star = new Block(8,6,"star");
let ladder = new Block(0,9,"ladder");
let box = new Block(5,5,"box");
wall.init();
star.init();
ladder.init();
box.init();